spring:
  application:
    name: chat-app

  datasource:
    url: jdbc:sqlite:chat.db
    driver-class-name: org.sqlite.JDBC

  kafka:
    bootstrap-servers: kafka-principal:9092

    consumer:
      group-id: chat-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
